### ISSUE TITLE
Onde baixar o .jar

### ISSUE THREAD

**Issue by thiagomoraesp** [opencs/AFTxWebDAVClient#2]
Oi pessoal, se essa dúvida não disser respeito a vocês por favor me avisem.
O Santander falou que eu vou ter que usar o AFT, me deu um manual mas não me deram o link para baixar, vocês sabem qual é?

**Comment by fjtc** [comment]
Olá. Thiago, esta dúvida você precisa consultar o próprio Santander. Eles é que dão o suporte ao produto AFT. Aqui só damos suporte a este projeto de código livre, que é um componente opcional do AFT do Santander.

Até...
